/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0b57a83b-35aa-4526-9e20-d889395aeb23",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EZKXXNawN",
    "aws_user_pools_web_client_id": "1ce7dp6ji51i579e45809g0vvb",
    "oauth": {}
};


export default awsmobile;
